export const DEFAULT_FIELDS_SET = [
    {name: "Product Name", value: "Super Product"},
    {name: "Project Description", value: "Attendant Solution position for Enterprise and Solutions asdasdasdasd"},
    {name: "Project Manager", value: "Super Manager"},
    {name: "Business Line Manager", value: "BLM"},
    {name: "Product Line Manager", value: "PLM"},
    {name: "Project State", value: "OPEN"},
    {name: "Project Rigor", value: "Low"},
    {name: "Charter", value: "Charter URL"},
    {name: "OR Business Plan", value: "OR BP"},
    {name: "Updated Business Plan", value: "Updated BP"},
    {name: "Tailored DR-checklist", value: "Tailored Info"},
    {name: "Lessons Learned", value: "Lessons"},
    {name: "Sponsor", value: "Rich Guy"},
    {name: "Business Division", value: "BD"},
    {name: "Business Unit", value: "BU"},
    {name: "Product Line", value: "PL"},
    {name: "PWS State", value: "Enabled"},
    {name: "Project Type", value: "OEM Product"},
    {name: "OEM Partner", value: "Super Partner"},
];